---
title: "MASDS Thesis - Exploratory Data Analysis"
author: "Lauren Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(utils)
library(dplyr)
library(purrr)
library(fs)
library(stringr)
library(ggplot2)
library(sf)
library(tmap)
library(cartogram)
library(stelfi)
library(lubridate)
library(hawkes)
library(MASS)
library(fitdistrplus)
library(PtProcess)
library(stats)
library(foreach)
library(sn)
library(geosphere)
library(spData)
library(sf)
library(tidyr)
library(geodist)
library(vegan)
library(ade4)
library(scales)
library(patchwork)
library(parallel)
library(reshape2)
```

# Read in the Data

```{r}
# parent directory containing relevant folders
parent_dir <- "C:/Users/cupca/Desktop/UCLA/Thesis"

# all folders within the parent directory
folder_list <- dir_ls(path = parent_dir, type = "dir")

# folders within the parent directory
folders <- c("2020", "2021", "2022", "2023")

# construct full paths to the specified directories
full_paths <- file.path(parent_dir, folders)

# a function to read and standardize columns of each csv file
read_and_standardize <- function(file) {
  df <- read.csv(file)
  # convert certain columns to the same format
  columns_to_convert <- c("Cases", "Case.Rate")
  # replace occurrences of -- with 0
  value_to_replace <- "--"
  # convert occurrences of the specific character value in the specified columns to integer 0
  df <- df %>%
  mutate(across(all_of(columns_to_convert), 
                 ~ ifelse(. == value_to_replace, 0, .))) %>%
  mutate(across(all_of(columns_to_convert), 
                 ~ as.numeric(as.character(.))))
  
  # standardize columns, add NA column if they do not exist
  if (!("Deaths" %in% names(df))) {
    df$Deaths <- NA
  }
  if (!("Death.Rate" %in% names(df))) {
    df$Death.Rate <- NA
  }
  return(df)
}

# read, combine all csv files from all folders
all_covid_data <- full_paths %>%
  # list all csv files in the folder
  map(~ dir_ls(path = .x, regexp = "\\.csv$", type = "file")) %>%
  # flatten list of file paths
  unlist() %>%
  # read, standardize each csv file
  map_df(read_and_standardize, .id = "source_id")

# save combined files to a new csv file
write.csv(all_covid_data, "all_covid_data.csv", row.names = FALSE)
```

## Data Cleaning

```{r}
# function that relabels source_id as Year
replace_if_contains <- function(df, substring_to_find, new_value) {
  # replace values with substring in specified column (source_id)
  df <- df %>%
    mutate(source_id = ifelse(str_detect(source_id, substring_to_find), new_value, source_id))
  return(df)
}

all_covid_data <- replace_if_contains(df=all_covid_data, substring_to_find="2020", new_value="2020")
all_covid_data <- replace_if_contains(df=all_covid_data, substring_to_find="2021", new_value="2021")
all_covid_data <- replace_if_contains(df=all_covid_data, substring_to_find="2022", new_value="2022")
all_covid_data <- replace_if_contains(df=all_covid_data, substring_to_find="2023", new_value="2023")

# rename column as Year
names(all_covid_data)[names(all_covid_data) == 'source_id'] <- 'year'

# Date Preprocessing

# extract month
all_covid_data$month <- substr(all_covid_data$date, nchar(all_covid_data$date) - 3, 
                               nchar(all_covid_data$date) - 2)

# extract day
all_covid_data$day <- substr(all_covid_data$date, nchar(all_covid_data$date) - 1, 
                             nchar(all_covid_data$date))

# create a column containing the full date (month, day, year)
all_covid_data$date <- as.Date(paste(all_covid_data$month, all_covid_data$day, all_covid_data$year), "%m%d%Y")

# drop individual month, day, year columns we no longer need
all_covid_data <- subset(all_covid_data, select = -c(year, month, day))

# new column called incidence, new deaths per day
all_covid_data <- all_covid_data %>%
  arrange(name, date) %>%
  group_by(name) %>%
  mutate(incidence = Deaths - lag(Deaths, default = 0)) %>%
  ungroup()

# replace negative, NA values in the deaths, incidence column with 0
all_covid_data <- all_covid_data %>%
  mutate(Deaths = ifelse(is.na(Deaths), 0, Deaths),
         incidence = ifelse(is.na(incidence) | incidence < 0, 0, incidence))

# convert date column to Date type, filter dates
community_data <- all_covid_data %>%
  mutate(date = as.Date(date)) %>%
  filter(date > 0) %>%
  filter(('2020-05-16' < date) & (date < '2023-01-02'))

# replace NA, 0 cases with 0.5 or 1
community_data <- community_data %>%
  mutate(Deaths = ifelse(is.na(Deaths), 0.5, Deaths),
         Deaths = ifelse(Deaths == 0, 0.5, Deaths))

# convert dates to numeric time (days since the start of the data)
start_date <- min(community_data$date, na.rm = TRUE)

community_data <- community_data %>%
  mutate(time = as.numeric(difftime(date, start_date, units = "days"))) %>%
  # remove invalid times
  filter(!is.na(time))
```

## Daily death incidence

prepare daily incidence data

```{r}
# Santa Monica
santa_monica <- community_data %>%
  filter(name == "City of Santa Monica")

# Silverlake
silverlake <- community_data %>%
  filter(name == "Los Angeles - Silverlake")

# Pomona
pomona <- community_data %>%
  filter(name == "City of Pomona")

# Glendale
glendale <- community_data %>%
  filter(name == "City of Glendale")

# El Monte
el_monte <- community_data %>%
  filter(name == "City of El Monte")

# Little Armenia
little_armenia <- community_data %>%
  filter(name == "Los Angeles - Little Armenia")

# Signal Hill
signal_hill <- community_data %>%
  filter(name == "City of Signal Hill")
```

prepare transformed event times for each community

```{r}
# cannot be simultaneous events, need to transform event times
generate_event_times <- function(time, deaths) {
  if (deaths > 0) {
    # distribute event times uniformly within the same day
    return(time + runif(deaths, min = 0, max = 1))  # random times
  } else {
    return(NULL)  # no deaths on this day
  }
}

# generate event times for each community
event_times <- community_data %>%
  group_by(name) %>%
  summarise(event_times = list(unlist(mapply(generate_event_times, time, incidence))))
# use death incidence instead of cumulative deaths

# Santa Monica
event_times_santa_monica <- event_times %>%
  filter(name == "City of Santa Monica") %>%
  pull(event_times)
# sort and get unique times
event_times_santa_monica <- sort(unlist(event_times_santa_monica))
event_times_santa_monica_unique <- unique(event_times_santa_monica)
adj_event_times_santa_monica <- event_times_santa_monica_unique + 
  seq(0, length(event_times_santa_monica_unique) - 1) * 1e-5

# Silverlake
event_times_silverlake <- event_times %>%
  filter(name == "Los Angeles - Silverlake") %>%
  pull(event_times)
# sort and get unique times
event_times_silverlake <- sort(unlist(event_times_silverlake))
event_times_silverlake_unique <- unique(event_times_silverlake)
adj_event_times_silverlake <- event_times_silverlake_unique + 
  seq(0, length(event_times_silverlake_unique) - 1) * 1e-5


# Pomona
event_times_pomona <- event_times %>%
  filter(name == "City of Pomona") %>%
  pull(event_times)
# sort and get unique times
event_times_pomona <- sort(unlist(event_times_pomona))
event_times_pomona_unique <- unique(event_times_pomona)
adj_event_times_pomona <- event_times_pomona_unique + 
  seq(0, length(event_times_pomona_unique) - 1) * 1e-5


# Glendale
event_times_glendale <- event_times %>%
  filter(name == "City of Glendale") %>%
  pull(event_times)
# sort and get unique times
event_times_glendale <- sort(unlist(event_times_glendale))
event_times_glendale_unique <- unique(event_times_glendale)
adj_event_times_glendale <- event_times_glendale_unique + 
  seq(0, length(event_times_glendale_unique) - 1) * 1e-5


# El Monte
event_times_el_monte<- event_times %>%
  filter(name == "City of El Monte") %>%
  pull(event_times)
# sort and get unique times
event_times_el_monte <- sort(unlist(event_times_el_monte))
event_times_el_monte_unique <- unique(event_times_el_monte)
adj_event_times_el_monte <- event_times_el_monte_unique + 
  seq(0, length(event_times_el_monte_unique) - 1) * 1e-5

# Little Armenia
event_times_little_armenia <- event_times %>%
  filter(name == "Los Angeles - Little Armenia") %>%
  pull(event_times)
# sort and get unique times
event_times_little_armenia <- sort(unlist(event_times_little_armenia))
event_times_little_armenia_unique <- unique(event_times_little_armenia)
adj_event_times_little_armenia <- event_times_little_armenia_unique + 
  seq(0, length(event_times_little_armenia_unique) - 1) * 1e-5

# Signal Hill
event_times_signal_hill <- event_times %>%
  filter(name == "City of Signal Hill") %>%
  pull(event_times)
# sort and get unique times
event_times_signal_hill <- sort(unlist(event_times_signal_hill))
event_times_signal_hill_unique <- unique(event_times_signal_hill)
adj_event_times_signal_hill <- event_times_signal_hill_unique + 
  seq(0, length(event_times_signal_hill_unique) - 1) * 1e-5
```


# Exploratory Data Analysis

```{r}
# choose subset from various areas of LA to look at death trends
subset_df <- all_covid_data %>%
  filter(name %in% c("City of Santa Monica",
                     "Los Angeles - Silverlake",
                     "City of Pomona",
                     "City of Glendale",
                     "City of El Monte",
                     "Los Angeles - Little Armenia",
                     "City of Signal Hill")) %>%
  mutate(daily_death_rate = (incidence / population) * 100000) 
# daily death rate is a similar concept to incidence, but wrt to population size and on a scale of per 100k people
```

```{r}
# summary statistics and tables

# table: total number of daily deaths (all communities)
overall_trend <- all_covid_data %>%
  group_by(date) %>%
  summarise(daily_deaths = sum(Deaths))

# table: total number of daily deaths by date for each community
community_trend <- all_covid_data %>%
  group_by(date, name) %>%
  summarise(daily_deaths = sum(Deaths), .groups = 'drop')

# table: total deaths in each community
total_deaths <- all_covid_data %>%
  group_by(name) %>%
  summarize(Deaths = sum(Deaths, na.rm = TRUE))

# table: aggregate daily deaths across all communities
subset_overall_trend <- subset_df %>%
  group_by(date) %>%
  summarise(daily_deaths = sum(Deaths))

# table: aggregate deaths by date and community
subset_community_trend <- subset_df %>%
  group_by(date, name) %>%
  summarise(daily_deaths = sum(Deaths), .groups = 'drop')
```

## Temporal Analysis

```{r, fig.width = 10}
# faceted barplot of death rate for subset communities
ggplot(subset_df, aes(x = date, y = Death.Rate, fill = name)) +
  geom_bar(stat = "identity") +
  labs(title = "Death rate across select LA communities over time",
       x = "Date", y = "Deaths per 100k people") +
  facet_wrap(~ name) +
  theme_bw()

# boxplot of death rate for subset communities
ggplot(subset_df, aes(x = name, y = Death.Rate)) +
  geom_boxplot(fill = "lightblue", color = "black") +
  labs(title = "Distribution of death rate across select LA communities",
       x = "Community", y = "Deaths per 100k people") +
  theme_bw()

# line plot of cumulative death rate for subset communities
ggplot(subset_df, aes(x = date, y = Death.Rate, color = name)) +
  geom_line() +
  facet_wrap(~ name, scales = "free_y") +
  labs(title = "Cumulative death rate across select LA communities over time", 
       x = "Date", 
       y = "Deaths per 100k people") +
  theme_bw()

# line plot of daily death rate for subset communities
ggplot(subset_df, aes(x = date, y = daily_death_rate, color = name)) +
  geom_line() +
  facet_wrap(~ name, scales = "free_y") +
  labs(title = "Daily death rate across select LA communities over time", 
       x = "Date", 
       y = "Daily death rate") +
  theme_bw()

# line plot of daily death incidence for subset communities
ggplot(subset_df, aes(x = date, y = incidence, color = name)) +
  geom_line() +
  facet_wrap(~ name, scales = "free_y") +
  labs(title = "Daily death incidence across select LA communities over time", 
       x = "Date", 
       y = "Daily death incidence") +
  theme_bw()
```

```{r}
# line plot of daily deaths for ALL communities
ggplot(overall_trend, aes(x = date, y = daily_deaths)) +
  geom_line(color = "blue") +
  labs(title = "Overall daily deaths for all LA communities", 
       x = "Date", y = "Number of deaths") +
  theme_bw()

# line plot of daily deaths for subset communities
ggplot(subset_overall_trend, aes(x = date, y = daily_deaths)) +
  geom_line(color = "blue") +
  labs(title = "Overall daily deaths across select LA communities", 
       x = "Date", y = "Number of deaths") +
  theme_bw()

# faceted line plot of daily deaths for each subset community
ggplot(subset_community_trend, aes(x = date, y = daily_deaths, color = name)) +
  geom_line() +
  facet_wrap(~ name, scales = "free_y") +
  labs(title = "Cumulative daily deaths across select LA communities over time", 
       x = "Date", y = "Number of deaths") +
  theme_bw()
```

## Geospatial Analysis

```{r}
# calculate total deaths and deaths per 100K for each community
community_deaths <- all_covid_data %>%
  group_by(name) %>%
  summarise(total_deaths = sum(Deaths, na.rm = TRUE),
            death_per_100k = (total_deaths / first(population)) * 100000)

# remove irrelevant values, replace NA with 0
community_deaths <- filter(community_deaths, !(name %in% c("FALSE", "Los Angeles")))
community_deaths[is.na(community_deaths)] <- 0

# read in geospatial data
geodata <- read_sf("C:/Users/cupca/Desktop/UCLA/Thesis/geospatial_data/CHP_2023_Data.shp")
geodata <- geodata %>% 
  dplyr::select(-"Geo_ID", -"Label") %>% 
  rename("name" = "Geo_Name") # drop unecessary columns

# prepare data
community_deaths <- all_covid_data %>%
  group_by(name) %>%
  filter(population > 1000) %>% # we will primarily be filtering pop > 1000, can also try pop > 5000
  summarize(total_deaths = sum(Deaths, na.rm = TRUE), # total deaths
            death_per_100k = (total_deaths / first(population)) * 100000, # overall death rate 2020-2023,
            population = first(population),
            incidence = sum(pmax(0, c(0, diff(Deaths[order(date)]))), na.rm = TRUE) # death incidence
  )

# join df with geo shape file
death_df <- geodata %>%
  right_join(community_deaths, by = "name")

# clean dataframe
death_df <- filter(death_df, 
                   !(Geo_Type %in% c("County",
                                     "Los Angeles City Council District", 
                                     "Service Planning Area", 
                                     "Supervisorial District")),
                   !(name %in% c("FALSE", "Los Angeles")))

# remove communities with empty geometry
death_df <- death_df[!sf::st_is_empty(death_df$geometry), ]

# replace NA with 0.5
death_df$total_deaths[is.na(death_df$total_deaths)] <- 0.5
death_df$death_per_100k[is.na(death_df$death_per_100k)] <- 0.5

# replace 0 with 0.5
death_df$total_deaths[(death_df$total_deaths == 0)] <- 0.5
death_df$death_per_100k[(death_df$death_per_100k == 0)] <- 0.5
```

```{r}
# distribution of death_per_100k
death_rate_hist_org <- ggplot(death_df, aes(x = death_per_100k)) +
  geom_histogram(binwidth = diff(range(death_df$death_per_100k)) / 100, 
                 fill = "lightblue", color = "black") +
  labs(title = "Histogram of death rate", 
       x = "Death rate (deaths/100k)", 
       y = "Count") +
  theme_bw()

# cubic transform
death_df$death_per_100k_cubic <- (death_df$death_per_100k)^(1/3)

death_rate_hist_cubic <- ggplot(death_df, aes(x = death_per_100k_cubic)) +
  geom_histogram(binwidth = diff(range(death_df$death_per_100k_cubic)) / 100, 
                 fill = "lightblue", color = "black") +
  labs(title = "Histogram of death rate (cubic root transform)", 
       x = "Death rate (deaths/100k)", 
       y = "Count") +
  theme_bw()

# distribution of total_deaths
total_death_hist_org <- ggplot(death_df, aes(x = total_deaths)) +
  geom_histogram(binwidth = diff(range(death_df$total_deaths)) / 100, 
                 fill = "lightblue", color = "black") +
  labs(title = "Histogram of total deaths", 
       x = "Total deaths", 
       y = "Count") +
  theme_bw()

# cubic transform
death_df$total_deaths_cubic <- (death_df$total_deaths)^(1/3)

total_death_hist_cubic <- ggplot(death_df, aes(x = total_deaths_cubic)) +
  geom_histogram(binwidth = diff(range(death_df$total_deaths_cubic)) / 100, 
                 fill = "lightblue", color = "black") +
  labs(title = "Histogram of total deaths (cubic root transform)", 
       x = "Total deaths", 
       y = "Count") +
  theme_bw()

death_rate_hist_org + total_death_hist_org
```

```{r}
# filter NA values
death_df <- death_df %>%
  filter(!is.na(total_deaths_cubic)) %>%
  filter(!is.na(death_df$death_per_100k_cubic))

# fix any invalid geometries
death_df$geometry <- st_make_valid(death_df$geometry)
```

```{r}
# choropleth map of death rate, no distortion
tm_shape(death_df) +
  tm_polygons("death_per_100k_cubic", 
              title = "Death rate (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```


```{r, fig.width = 8}
# death_per_100k cubic transform

# choropleth + cartogram
avg_deaths_cont_cubic <- cartogram_cont(death_df, "death_per_100k_cubic", itermax = 5)
tm_shape(avg_deaths_cont_cubic) +
  tm_polygons("death_per_100k_cubic", 
              title = "Death rate (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```

```{r}
# get highest death_per_100k_cubic (death rate with cubic transform) communities
death_df %>%
  dplyr::select(name, death_per_100k_cubic) %>%
  arrange(-death_per_100k_cubic)

# Top 3 highest death rate (cubic) communities
# pop > 1000: Little Armenia, Unincorporated La Rambla, St Elmo Village
# pop > 5000: Little Armenia, Unincorporated West Carson, Pico-Union
```

```{r}
# total_deaths cubic transform
total_deaths_cont_cubic <- cartogram_cont(death_df, "total_deaths_cubic", itermax = 5)

# just choropleth map, no distortion
tm_shape(death_df) +
  tm_polygons("total_deaths_cubic", 
              title = "Total deaths (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```

```{r, fig.width = 8}
# plot
tm_shape(total_deaths_cont_cubic) +
  tm_polygons("total_deaths_cubic", 
              title = "Total deaths (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```

```{r}
# get highest total_deaths_cubic (total deaths with cubic transform) communities
death_df %>%
  dplyr::select(name, total_deaths_cubic) %>%
  arrange(-total_deaths_cubic)

# Top 3 highest total deaths (cubic) communities
# pop > 1000: City of Glendale, City of Pomona, City of El Monte
# pop > 5000: City of Glendale, City of Pomona, City of El Monte
```

```{r}
# cubic root transform of population
death_df$population_cubic <- (death_df$population)^(1/3)

# just choropleth map of population, no distortion
tm_shape(death_df) +
  tm_polygons("population_cubic", 
              title = "Population (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```

```{r}
# cartogram distorted by population, color by death rate
pop_cont_cubic <- cartogram_cont(death_df, "population_cubic", itermax = 5)

tm_shape(pop_cont_cubic) +
  tm_polygons("death_per_100k_cubic", 
              title = "Population (color), death rate (distortion) (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```
```{r}
# get highest death_per_100k_cubic, population (with cubic transform) communities
death_df %>%
  dplyr::select(name, death_per_100k_cubic, population_cubic) %>%
  arrange(-population_cubic, death_per_100k_cubic)

# Top 3 highest population density (cubic) communities
# pop > 1000: City of Santa Clarita, City of Glendale, City of Lancaster
# pop > 5000: City of Santa Clarita, City of Glendale, City of Lancaster
```

```{r}
# cartogram distorted by population, color by total deaths
pop_cont_cubic <- cartogram_cont(death_df, "population_cubic", itermax = 5)

tm_shape(pop_cont_cubic) +
  tm_polygons("total_deaths_cubic", 
              title = "Population (color), total deaths (distortion) (cubic)",
              style = "quantile",    # use quantiles
              n = 10                # deciles = 10 bins
              ) +
  tm_layout(frame = FALSE, legend.position = c("left", "bottom"), legend.frame = FALSE)
```

```{r}
# get highest total_deaths_cubic, population (with cubic transform) communities
death_df %>%
  dplyr::select(name, total_deaths_cubic, population_cubic) %>%
  arrange(-population_cubic, total_deaths_cubic)

# Top 3 highest population density (cubic) communities
# pop > 1000: City of Santa Clarita, City of Glendale, City of Lancaster
# pop > 5000: City of Santa Clarita, City of Glendale, City of Lancaster
```

## Age Distribution

```{r}
# age distribution data (age groups)
age_labels <- c("0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+")

# santa monica
age_data_sm <- c(5544, 6775, 9767, 18200, 11240, 12473, 11598, 8768, 5574) # census reporter

# silverlake
age_data_s <- c(3180, 2920, 5040, 5760, 4950, 3240, 2160, 1440, 900) # city data

# pomona
age_data_p <- c(15552, 17071, 22673, 23058, 20584, 18582, 15188, 8959, 3822) # census reporter

# glendale
age_data_g <- c(16839, 20343, 20629, 28874, 26031, 23322, 24892, 17068, 9034) # census reporter

# el monte
age_data_em <- c(10628, 15791, 14855, 12717, 12851, 13337, 12408, 7863, 3332) # census reporter

# little armenia
age_data_la <- c(2790, 2835, 3510, 3600, 2700, 1980, 1530, 1215, 720) # city data

# signal hill
age_data_sh <- c(981, 1240, 1360, 2127, 1782, 1759, 1400, 558, 356) # census reporter

# histograms of age distribution
age_data <- data.frame(
  Age_Group = rep(age_labels, 7),
  Population = c(age_data_sm, age_data_s, age_data_p, age_data_g, age_data_em, age_data_la, age_data_sh),
  Community = rep(c("Santa Monica", "Silverlake", "Pomona", "Glendale", "El Monte", 
                    "Little Armenia", "Signal Hill"), each = 9))

# histogram bar chart
age_dist <- ggplot(age_data, aes(x = Age_Group, y = Population, fill = Community)) +
  geom_bar(stat = "identity", position = "dodge") + 
  facet_wrap(~Community, scales = "free_y") + 
  labs(title = "Age distribution by community",
       x = "Age group",
       y = "Population") +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(age_dist)
```

```{r}
# correlation between age group and deaths
age_data <- rbind(
  age_data_sm,  # Santa Monica
  age_data_s,   # Silverlake
  age_data_p,   # Pomona
  age_data_g,   # Glendale
  age_data_em,  # El Monte
  age_data_la,  # Little Armenia
  age_data_sh   # Signal Hill
)

rownames(age_data) <- c("Santa Monica", "Silverlake", "Pomona", "Glendale", 
                        "El Monte", "Little Armenia", "Signal Hill")

colnames(age_data) <- c("0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+")

# normalize age distribution
age_proportions <- age_data / rowSums(age_data)

# total deaths in each community
incidence_list <- list(
  "Santa Monica" = santa_monica$incidence,
  "Silverlake" = silverlake$incidence,
  "Pomona" = pomona$incidence,
  "Glendale" = glendale$incidence,
  "El Monte" = el_monte$incidence,
  "Little Armenia" = little_armenia$incidence,
  "Signal Hill" = signal_hill$incidence
)
death_counts <- sapply(incidence_list, sum)

# correlation between age props and death occurrences
cor_results <- apply(age_proportions, 2, 
                     function(age_col) cor(age_col, death_counts, method = "spearman"))
print(cor_results)
```

### Mantel clustering test

```{r}
geodata <- read_sf("C:/Users/cupca/Desktop/UCLA/Thesis/geospatial_data/CHP_2023_Data.shp")
geodata <- geodata %>% 
  dplyr::select(-"Geo_ID", -"Label") %>% 
  rename("name" = "Geo_Name") # drop unecessary columns

# filter communities, get lon and lat values from centroids
geodata_subset <- geodata %>%
  filter(name %in% c("City of Santa Monica",
                     "Los Angeles - Silverlake",
                     "City of Pomona",
                     "City of Glendale",
                     "City of El Monte",
                     "Los Angeles - Little Armenia",
                     "City of Signal Hill")) %>%
  group_by(name) %>%
  mutate(centroid = st_centroid(geometry)) %>% # get centroid
  transmute(name, 
            lon = st_coordinates(centroid)[,1], 
            lat = st_coordinates(centroid)[,2]) # get lon/lat

# convert polygon coordinates to standard lon, lat
geodata <- st_transform(geodata, 4326)
```

```{r}
# spatial distance matrix

# matrix of spatial distances
coords <- geodata_subset[, c("lon", "lat")]
spatial_dist_matrix <- geodist(coords, measure = "haversine")  # distance (m)

# convert to standard distance object
spatial_dist <- as.dist(spatial_dist_matrix)

# prepare event time data
event_times_santa_monica_df <- as.data.frame(adj_event_times_santa_monica[[1]])
colnames(event_times_santa_monica_df) <- "event_times"

event_times_silverlake_df <- as.data.frame(adj_event_times_silverlake[[1]])
colnames(event_times_silverlake_df) <- "event_times"

event_times_pomona_df <- as.data.frame(adj_event_times_pomona[[1]])
colnames(event_times_pomona_df) <- "event_times"

event_times_glendale_df <- as.data.frame(adj_event_times_glendale[[1]])
colnames(event_times_glendale_df) <- "event_times"

event_times_el_monte_df <- as.data.frame(adj_event_times_el_monte[[1]])
colnames(event_times_el_monte_df) <- "event_times"

event_times_little_armenia_df <- as.data.frame(adj_event_times_little_armenia[[1]])
colnames(event_times_little_armenia_df) <- "event_times"

event_times_signal_hill_df <- as.data.frame(adj_event_times_signal_hill[[1]])
colnames(event_times_signal_hill_df) <- "event_times"

# calculate mean event times
mean_event_times <- c(mean(event_times_santa_monica_df$event_times),
                      mean(event_times_silverlake_df$event_times),
                      mean(event_times_pomona_df$event_times),
                      mean(event_times_glendale_df$event_times),
                      mean(event_times_el_monte_df$event_times),
                      mean(event_times_little_armenia_df$event_times),
                      mean(event_times_signal_hill_df$event_times))

# calculate pairwise differences in event times
temporal_dist_matrix <- as.matrix(dist(mean_event_times))

# convert to standard distance object
temporal_dist <- as.dist(temporal_dist_matrix)
```

```{r}
# Mantel test
mantel_result <- mantel(spatial_dist, temporal_dist, 
                        method = "pearson", permutations = 9999)
print(mantel_result)
```

